package com.galvanize;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() { return "hello world"; }
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
